"""initial_schema

Revision ID: 00260ac0f411
Revises: 004
Create Date: 2026-06-13 18:32:03.425140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '00260ac0f411'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('user', 'assistant', 'system', name='message_role', native_enum=False),
               existing_nullable=False)
    op.alter_column('embeddings', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=False)
    op.drop_index('ix_embeddings_vector_hnsw', table_name='embeddings', postgresql_using='hnsw')
    op.drop_constraint('uq_embeddings_chunk_id', 'embeddings', type_='unique')
    op.drop_index('ix_embeddings_chunk_id', table_name='embeddings')
    op.create_index(op.f('ix_embeddings_chunk_id'), 'embeddings', ['chunk_id'], unique=True)
    op.alter_column('sources', 'source_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('github', 'obsidian', 'local_files', 'manual', name='source_type', native_enum=False),
               existing_nullable=False)
    op.alter_column('sources', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'ready', 'syncing', 'failed', name='source_status', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_workspaces_owner_id_created_at', table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspaces_owner_id_created_at', 'workspaces', ['owner_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('sources', 'status',
               existing_type=sa.Enum('pending', 'ready', 'syncing', 'failed', name='source_status', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('sources', 'source_type',
               existing_type=sa.Enum('github', 'obsidian', 'local_files', 'manual', name='source_type', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_embeddings_chunk_id'), table_name='embeddings')
    op.create_index('ix_embeddings_chunk_id', 'embeddings', ['chunk_id'], unique=False)
    op.create_unique_constraint('uq_embeddings_chunk_id', 'embeddings', ['chunk_id'])
    op.create_index('ix_embeddings_vector_hnsw', 'embeddings', ['vector'], unique=False, postgresql_using='hnsw')
    op.alter_column('embeddings', 'vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.Enum('user', 'assistant', 'system', name='message_role', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
